### ISSUE TITLE
Excellent React component but some concerns

### ISSUE THREAD

**Issue by topgun743** [subschema/subschema#24]
Hi Justin,
Your work is remarkable. Its an excellent component but here are some concerns:

1. Documentation needs to be improved. It should be clear. At some points it is hard to understand what exactly is meant. e.g It took me sometime to understand following, that this will be done ahead :)
`DateTime`
`Barely a component, but oneday it will be made useful`

2. How should I provide the label of my field like 
`PersonAge: {
      type: Number,
      label: 'Your Age'
}`

3. I could not understand how to provide validators for a field through schema especially via a custom function. Please guide about this in your documentation and demo. It would be better if these validators are provided like in the following:
https://github.com/SteveVitali/react-form-generator#formfield-validators

4. No information regarding how the the overall layout of a form should be provided in schema so that for example Form field groups could be placed in a vertical layout. Bootstrap indeed provides us options for it:
Example  a form in vertical layout: 

`Name`   

 `Input Field here`

`Age`

`Input field here`

So Form layout should be configurable via schema.

5. It would be very nice if you provide something like `objectField, arrayOfObjectsField, arrayOfArraysField, arrayOfArrayOfArrayOfObjectsField` as in the following:
https://github.com/SteveVitali/react-form-generator#formfield-validators
This I guess is like your custom type but that contains a set (or multiple set) of fields.

That was just my feedback. I hope you will like it and look to my mentioned concerns. Counting on you. Thanks

[Update] Also how to populate actual data on a Form. An example is needed.

**Comment by jspears** [comment]
Hey thanks for the feedback.
Fair enougth.
1.) Agreed, working on it. I was hoping the [https://jspears.github.io/subschema](https://jspears.github.io/subschema) site would be enough.

2) The title attribute is what you are looking for
```js
 {
  YourField:{
    type:'Text',
   title:'Your Title'
  }
```
Title can be a content object if you need more fine grained dom.  

3)  I want the schema to be pure json.   While it is tempting to add JS in there, it breaks it.   So its a trade off.    You can add custom validators like this.  I think its better,because its json, second because the validators are easily reusable.   Once you create a custom validator, you don't have to do anything but reference.

Example below.


```js
var loader = require('subschema/loader');
  loader.addValidator('yourValidator', function(options){
    //options
   return function(){
   //do your validation here.
    } 
});
```
Then in your schema
```js
  var schema = {
     schema:{
     'Hello:{
       type:'Text',
      validators:['required', 'yourValidator']
    }
    }
  }

``` 



4) Forms can take template attribute but should be in the docs.
```jsx
  loader.addTemplate('yourTemplate, ...);
  <Form template='yourTemplate'/>
```
agreed that form layout should be able to happen via schema.    I'm thinking of extending the schema like this.
```js
{
  schema:{},
  fieldsets:[{fields:[], template:'', buttons:[]}],
  template:'YourTemplate',
  loaders:{
    'templates':{
      'YourTemplate':'../../YourTemplate.jsx'
    },
   'types':{
      'YourType':'../yourType'
    },
    validators:{},
    operators:{},
   }
}
```
The new webpack loader for subschema, will automatically determine these for you and only include the ones that are provided.   I understand it doesn't work for everyone (non webpack users) so...  Really though in this day everyone who writes JS should use webpack.   It has changed web dev for me more than any other tech in the last 18 years, with maybe jQuery being the other one.

The subschema site app gives examples for almost all of the functionality.   It may answer many of your questions.  I built it so I could keep docs in sync with the app, however it gh_pages are a real pain.

**Comment by topgun743** [comment]
Thanks Justin for reply. Will check the template prop of forms. Good to know that you will make it further ease down establishing layout of the form overall.
One more thing on your example site, there was no Form example with Save/Cancel button. Thereshould be at least one that should help us know how to place one Save button, bind it to the Form component and catch its submit event. Better with some Ajax mixin if possible. 
I can use jjQuery for this but want to know how is it possible while remaining in the React plus subschema ethics.

**Comment by jspears** [comment]
Good point on the save cancel.
it is possible already with buttons:[] in the fieldset.  I will add an example in a few.

**Comment by topgun743** [comment]
Just checked your latest work regarding Submit/Close on:
http://jspears.github.io/subschema/?title=Mr&name=&email=#/Modal
Really nice.
But I could not understand where the binding to submit button's click event is done and how it is handled then. Guess some code related to it is not shown on demo.

Also what about if some UI portion changes based upon action for example on change of one dropdown's selection. How this can be done? Asking this because in a large form some fields depend upon the selection of some other field on form.

**Comment by topgun743** [comment]
Hi Justin,
Have you done anything regarding your proposed change in your last comment: 
"Form layout should be able to happen via schema"?

Also can you please tell that at present via schema, against a field, how can we set its options (radios or checkboxes) in a horizontal layout. At present in your examples they are vertically laid.

Thanks

**Comment by jspears** [comment]
Yes lots of progress in the react14-move branch.  Hopefully have it out soon.

As for horizontal checkboxes, that can be done by CSS only or by creating a new template
```js
loader.addTemplate('CheckboxesTemplate', React.createClass({
   render(){
   return <label className='checkbox-inline'>
                {this.props.children}
                {this.props.label}
            </label>
  }

}))

```


I guess I could make the CSS class an option, in the checkboxes component.

**Comment by jspears** [comment]
I think I addressed everything except maybe the docs, but closing anyways as it really is too many things. Open an issue per remaining concern.
