### ISSUE TITLE
File size of library

### ISSUE THREAD

**Issue by alexandernst** [subschema/subschema#46]
I'm trying to build this library, but the file size in the `dist` folder is about `4.1 MBs`, which doesn't look right.
Anyways, after looking at the demos, I saw that the dist file is around `1.7 MBs`, which also doesn't look right.

Is this library actually that big or is that just some misconfiguration of webpack?

**Comment by jspears** [comment]
It's not that big.  I regularly do production app builds less than 800k, with a bunch of other stuff.  The demo is huge because it includes all of babel to do client side evaluation of ES6/JSX code.   In addition it includes a complete copy of subschema and react for the demo.    So its  a bit huge.   

The dist folder includes several distributions, and sourcemaps.  The sourcemaps are generally bigger than the source.

**Comment by alexandernst** [comment]
You're right. I spent some more time and the final result is ~300KB (the `noreact` version).
I'm wondering if that size can be further reduced somehow? Are you using uglify somewhere?
