### ISSUE TITLE
Default value of select doesn't trigger conditional operator

### ISSUE THREAD

**Issue by alexandernst** [subschema/subschema#49]
I have a select with 2 options. Each option has a conditional field that shows more fields, based on the selection of the main select.

On page load, the conditional field isn't executed and because of that the rest of the inputs remain hidden.

Is there a way I can make subschema run the conditional fields on page load?

**Comment by Angelmmiguel** [comment]
I think the issue comes from `Select` component. The value of this component is [initialized to a dot](https://github.com/subschema/subschema/blob/master/src/types/Select.jsx#L26) by default and `onChange` callback is not executed when the component is mounted. Check the following example from the [Subschema page](http://subschema.github.io/subschema/#/Wizard?_k=r4bt5s):

![Select initialization](https://cloud.githubusercontent.com/assets/4056725/17372286/7af30ad4-59a3-11e6-84bc-b5dd9a9b130a.png)

A possible solution is to receive `value` as a prop in `Select` component and call `onChange` on `componentDidMount` method. However, I don't see any example with a `value` property in a selector so I don't know if this approach have some unexpected problem @jspears

**Comment by speajus2** [comment]
Conditionals are executed against the changes to the values in the ValueManager.   One possible solution is to move the conditional to the top level field.   The problem as I understand it isn't that the onChange isn't fired.  Its that the listeners don't exist for that field. 

So you can add conditionals per field or per fieldset.  The depth of conditional will be what burns you.

**Comment by alexandernst** [comment]
@speajus2 I think we're already trying that, but it's not working. Please see a minimal repro case/demo: https://jsbin.com/fomobapixe/2/edit?html,js,output

**Comment by jspears** [comment]
house keeping if it still an issue or you still care about it let me know
